################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
BLE/App/BLECmdHandlerLiaison.obj: ../BLE/App/BLECmdHandlerLiaison.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLECmdHandlerLiaison.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEGATTCalSvc.obj: ../BLE/App/BLEGATTCalSvc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEGATTCalSvc.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEGATTCmdSvc.obj: ../BLE/App/BLEGATTCmdSvc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEGATTCmdSvc.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEGATTConfSvc.obj: ../BLE/App/BLEGATTConfSvc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEGATTConfSvc.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEGATTGISvc.obj: ../BLE/App/BLEGATTGISvc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEGATTGISvc.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEGATTScanSvc.obj: ../BLE/App/BLEGATTScanSvc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEGATTScanSvc.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEGATTStdSvcs.obj: ../BLE/App/BLEGATTStdSvcs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEGATTStdSvcs.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEGATTTimeSvc.obj: ../BLE/App/BLEGATTTimeSvc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEGATTTimeSvc.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEMain.obj: ../BLE/App/BLEMain.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEMain.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLENotificationHandler.obj: ../BLE/App/BLENotificationHandler.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLENotificationHandler.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEProfMgr.obj: ../BLE/App/BLEProfMgr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEProfMgr.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/BLEUtils.obj: ../BLE/App/BLEUtils.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/BLEUtils.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BLE/App/TivaWareLib.obj: ../BLE/App/TivaWareLib.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.5/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Common/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.2/src" --include_path="C:/ti/tirtos_tivac_2_10_01_38/products/TivaWare_C_Series-2.1.0.12573c" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Drivers/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/Board/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btpsvend" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/btvs/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/App/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/bas/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/include" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Bluetopia/profiles/dis/source" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware" --include_path="C:/ti/DLPNIRscanNanoSoftware_2.0.1/Sources/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_wrap=off --display_error_number --diag_warning=225 --preproc_with_compile --preproc_dependency="BLE/App/TivaWareLib.pp" --obj_directory="BLE/App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


